spring:
  application:
    name: gnews-mock-api
  datasource:
    url: jdbc:h2:mem:gnewsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

gnews:
  api-key: "test-api-key"
  rate-limit:
    daily-requests: 100
